### ISSUE TITLE
TASK 1 - Computer Setup

### ISSUE THREAD

**Issue by maxtondelaney** [AlamedaTony/repository-test#1]
Make sure when you're developing that you're on your Mac. You're going to need to make sure some basic stuff is installed, you may have some of this already.

Homebrew - https://brew.sh/
This is a package manager for MacOSX, you can install software directly by using it.

ITerm2 - https://iterm2.com/
A better terminal for MacOSX. Let's you do custom themes, etc.

NVM - https://formulae.brew.sh/formula/nvm
Node Version Manager, it's somewhat common to need to switch versions of Node on the fly depending on how old or new a project is. 

Node.js - https://nodejs.org/en/ 
JavaScript runtime, used to run Javascript code on a server. You will use NVM to install this.

In your terminal, run `nvm install 17`

yarn - https://yarnpkg.com/
Package manager for Node, one of the best ones. You'll be able to install it using Homebrew: https://formulae.brew.sh/formula/yarn. 

You'll need to setup Git on your computer, this is preinstalled with MacOSX. The biggest thing is setting up SSH access for GitHub, this will make developing and pushing code to your repositories much easier. https://docs.github.com/en/authentication/connecting-to-github-with-ssh

If you don't have an IDE, I recommend using VSCode: https://code.visualstudio.com/

**Comment by AlamedaTony** [comment]
installed everything via the sent links.
