### ISSUE TITLE
TASK 2 - Project Setup

### ISSUE THREAD

**Issue by maxtondelaney** [AlamedaTony/repository-test#2]
Once your computer is setup, it's time to configure the project. For this project, we are going to use a script that initializes a boilerplate React project. This is known as Create React App. We will use the Typescript variant - Typescript is extremely popular and it's better if you learn it now.

If you want to learn more about Typescript, see: https://www.youtube.com/watch?v=zQnBQ4tB3ZA

Here are the install instructions for Create React App: https://create-react-app.dev/docs/adding-typescript/

During the installation, change the name from "my-app" to "fitness-journal". 

You may close this ticket once you have done this, ran the boilerplate application and posted a screenshot in the comments, and put up a code review that I have approved.

Time box this for 2 hours.

**Comment by AlamedaTony** [comment]
<img width="1440" alt="Screen Shot 2022-01-28 at 4 59 31 PM" src="https://user-images.githubusercontent.com/89045523/151640531-7318aa03-8e0f-4ae8-ad6c-d6d73534bd42.png">

This is what i got after doing the instructions from the attached link and changing the name, i think.
