### ISSUE TITLE
TASK 3 - Tutorial

### ISSUE THREAD

**Issue by maxtondelaney** [AlamedaTony/repository-test#3]
Now that the project is setup and you know how to run it, it's important that you watch a React tutorial and attempt to follow along. Your goal is to finish the tutorial and open a code review for your code changes, we will build upon this code so don't think you're wasting your time.

First watch this video to learn about React: https://www.youtube.com/watch?v=Tn6-PIqc4UM

Then complete the following tutorial: https://www.youtube.com/watch?v=bjnW2NLAofI (seemed okay, didn't watch all of it)

Don't worry if you don't know what's going on, it takes a while to figure it all out. The point is to learn the 'muscle movements'.

**Comment by AlamedaTony** [comment]
Completed
